export const keyboardMappings = {
    "arrow-named": {
        "shoulder-left": "l",
        "shoulder-right": "r",
        "dpad-up": "ArrowUp",
        "dpad-left": "ArrowLeft",
        "dpad-right": "ArrowRight",
        "dpad-down": "ArrowDown",
        "action-primary": "a",
        "action-secondary": "b",
    },
    "arrow-qwas": {
        "shoulder-left": "q",
        "shoulder-right": "w",
        "dpad-up": "ArrowUp",
        "dpad-left": "ArrowLeft",
        "dpad-right": "ArrowRight",
        "dpad-down": "ArrowDown",
        "action-primary": "a",
        "action-secondary": "s",
    },
    wasd: {
        "shoulder-left": "2",
        "shoulder-right": "3",
        "dpad-up": "w",
        "dpad-left": "a",
        "dpad-right": "d",
        "dpad-down": "s",
        "action-primary": "k",
        "action-secondary": "l",
    },
    "wasd-space-shift": {
        "shoulder-left": "e",
        "shoulder-right": "f",
        "dpad-up": "w",
        "dpad-left": "a",
        "dpad-right": "d",
        "dpad-down": "s",
        "action-primary": " ",
        "action-secondary": "Shift",
    },
};
