export const keyboardMappings = {
    "arrow-named": {
        "bumper-left": "l",
        "bumper-right": "r",
        "trigger-left": "t",
        "trigger-right": "z",
        "dpad-up": "ArrowUp",
        "dpad-left": "ArrowLeft",
        "dpad-right": "ArrowRight",
        "dpad-down": "ArrowDown",
        "face-south": "a",
        "face-east": "b",
        "face-west": "x",
        "face-north": "y",
    },
    "arrow-qwas": {
        "bumper-left": "1",
        "bumper-right": "2",
        "trigger-left": "e",
        "trigger-right": "d",
        "dpad-up": "ArrowUp",
        "dpad-left": "ArrowLeft",
        "dpad-right": "ArrowRight",
        "dpad-down": "ArrowDown",
        "face-south": "a",
        "face-east": "s",
        "face-west": "q",
        "face-north": "w",
    },
    wasd: {
        "bumper-left": "1",
        "bumper-right": "2",
        "trigger-left": "3",
        "trigger-right": "4",
        "dpad-up": "w",
        "dpad-left": "a",
        "dpad-right": "d",
        "dpad-down": "s",
        "face-south": "k",
        "face-east": "l",
        "face-west": "j",
        "face-north": "i",
    },
    "wasd-space-slash": {
        "bumper-left": "e",
        "bumper-right": "f",
        "trigger-left": "z",
        "trigger-right": "x",
        "dpad-up": "w",
        "dpad-left": "a",
        "dpad-right": "d",
        "dpad-down": "s",
        "face-south": " ",
        "face-east": "/",
        "face-west": ",",
        "face-north": ".",
    },
};
